# JanusGraph HBase config for bulk / batch loading (not for OLTP server use)
storage.backend=hbase
storage.hostname=127.0.0.1
storage.port=2181
storage.hbase.table=janusgraph

storage.batch-loading=true
schema.default=none

cache.db-cache=true
cache.db-cache-clean-wait=20
cache.db-cache-time=180000
cache.db-cache-size=0.5

storage.buffer-size=8192
storage.write-time=100000
ids.block-size=100000
ids.renew-percentage=0.3

graph.replace-instance-if-exists=true
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.setup-wait=300000
storage.hbase.ext.hbase.rpc.timeout=300000
storage.hbase.ext.hbase.client.operation.timeout=300000
ids.authority.wait-time=5000
ids.authority.random-bound=0
storage.hbase.ext.hbase.client.durability=ASYNC_WAL
storage.hbase.ext.hbase.client.write.buffer=8388608
